# Site settings
title: Jeff Gilbert - web developer and chief bottle washer
email: jwgebdev@gmail.com 
description: "This will be a journal of my adventures in the world of web development. I hope to have lots of stories about the cool stuff I do with HTML, CSS, javaScript, etc. Stay tuned and feel free to join in the fun!"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
